#! /usr/bin/env python3
# print all possible Zero motorcycle Bluetooth packets

import base64
import zerobt

socket=zerobt.connect_to_bike()

try:
    print('Name:', zerobt.name)
    print('Addr:', zerobt.addr)
    print('Port:', zerobt.port)
    print()

    for cmd in sorted(zerobt.cmd_packets):
        packet=zerobt.read_packet(socket, cmd)
        print('command:', cmd)
        print('packet:', base64.b64encode(zerobt.cmd_packets[cmd]))
        for key in sorted(packet):
            print(key+':', packet[key])
        print()
finally:
    socket.close()
