#! /usr/bin/env python3
# gather all possible Zero motorcycle Bluetooth packets for code demo

import zerobt

socket=zerobt.connect_to_bike()

try:
    print('name='+repr(zerobt.name))
    print('addr='+repr(zerobt.addr))
    print('port='+repr(zerobt.port))
    for cmd in sorted(zerobt.cmd_packets):
        packet=zerobt.read_packet(socket, cmd)
        print(cmd.lower()+'='+repr(packet))
finally:
    socket.close()
