#! /usr/bin/env python3
# print charging info suitable for Excel

import zerobt

def c2f(c):
   return (c*9/5)+32

socket=zerobt.connect('00:06:66:1C:BA:7A', 1)
try:
    pwpk=zerobt.read_packet(socket, 'PwPk')
    dst3=zerobt.read_packet(socket, 'DSt3')

    t=dst3['minutes_until_charged']
    h, m=divmod(t, 60)
    print('time remaining: %d:%02d  min temp: %.1f  max temp: %.1f  voltage: %.1f  percentage: %d' %
          (h, m, c2f(pwpk['pack_temp_min_c']), c2f(pwpk['pack_temp_max_c']),
           pwpk['pack_voltage_mv']/100.0, pwpk['charge_pct']))
finally:
    socket.close()
