#! /usr/bin/env python3
# print charging info suitable for Excel

import sys
import time
import zerobt

# wait for bike to become available
zerobt.get_services(retries=100, callback=lambda: print('retrying...', file=sys.stderr))

print('connecting...', file=sys.stderr)
socket=zerobt.connect_to_bike()
print('connected to bike', file=sys.stderr)

try:
    # wait until we're charging
    while True:
        print('reading MbbR packet', file=sys.stderr)
        mbbr=zerobt.read_packet(socket, 'MbbR')
        if mbbr['charging']:
            break
        time.sleep(30)

    # header line
    print('"Time"',
          '"Time\nUntil\nCharged"',
          '"Battery\nCurrent\n(amps)"', '"Cell\nVoltage\nMax\n(mV)"', '"Cell\nVoltage\nMin\n(mV)"',
          '"Pack\nCapacity\n(ah)"', '"Pack\nCapacity\nRemain\n(ah)"', '"Pack\nTemp\n1 (°C)"', '"Pack\nTemp\n2 (°C)"',
          '"Pack\nTemp\n3 (°C)"', '"Pack\nTemp\n4 (°C)"', '"Pack\nTemp\n5 (°C)"', '"Pack\nTemp\n6 (°C)"',
          '"Pack\nTemp\n7 (°C)"', '"Pack\nTemp\n8 (°C)"', '"Pack\nTemp\nMax (°C)"', '"Pack\nTemp\nMin (°C)"',
          '"Pack\nVoltage\n(mV)"', '"Charge\n(%)"', sep=',', flush=True)

    ctr=5
    while ctr:
        now=time.strftime('%H:%M:%S')

        mbbr=zerobt.read_packet(socket, 'MbbR')
        if mbbr['charging']:
            ctr=5
        else:
            ctr-=1
            continue
        if mbbr['battery_current_amps']:
            ctr=5
        else:
            ctr-=1
            continue

        pwpk=zerobt.read_packet(socket, 'PwPk')
        dst3=zerobt.read_packet(socket, 'DSt3')

        t=dst3['minutes_until_charged']
        h, m=divmod(t, 60)

        print(now, '%d:%02d' % (h, m),
              pwpk['battery_current_amps'], pwpk['cell_voltage_max_mv'], pwpk['cell_voltage_min_mv'],
              pwpk['pack_capacity_ah'], pwpk['pack_capacity_remain_ah'], pwpk['pack_temp_1_c'], pwpk['pack_temp_2_c'],
              pwpk['pack_temp_3_c'], pwpk['pack_temp_4_c'], pwpk['pack_temp_5_c'], pwpk['pack_temp_6_c'],
              pwpk['pack_temp_7_c'], pwpk['pack_temp_8_c'], pwpk['pack_temp_max_c'], pwpk['pack_temp_min_c'],
              pwpk['pack_voltage_mv'], pwpk['charge_pct'], sep=',', flush=True)

        time.sleep(60)
finally:
    socket.close()
