#! /usr/bin/env python3
# demonstrate how to extract packets from a ride and write to csv for a spreadsheet
#
# Run using:
# extract_ride ride.dat

import os
import sys
import pickle

# read packets
fn=sys.argv[1]
f=open(fn, 'rb')
unpickler=pickle.Unpickler(f)
packets=[]
while True:
    try:
        packets.append(unpickler.load())
    except EOFError:
        break
f.close()

# open output
fn, x=os.path.splitext(fn)
f=open(fn+'.csv', 'w')

# header line
print('"Time"', '"Speed"', '"RPM"', '"Range"', '"Pack\nTemp\nMax (°C)"', '"Pack\nTemp\nMin (°C)"',
      '"Battery\nCurrent\n(amps)"', '"Motor\nCurrent\n(amps)"', '"Charge\n(%)"', '"Kickstand"',
      '"Motor\nTorque\nNM"', sep=',', file=f)

data_set=None
for packet in packets:
    if data_set != packet['set'] and data_set != None:
        # we've reached the end of the data set, print the data line
        print(time, speed, rpm, range, pack_max, pack_min, battery_current, motor_current,
              charge, kickstand, torque, sep=',', file=f)
        data_set=packet['set']
    time=packet['time']
    if packet['type'] == 'MbbR':
        speed=packet['bike_speed_mph']
        rpm=packet['motor_speed_rpm']
        torque=packet['motor_torque_nm']
        kickstand=packet['kickstand_down']
    elif packet['type'] == 'DSt2':
        range=packet['est_range_km']*1.609
    elif packet['type'] == 'PwPk':
        pack_min=packet['pack_temp_min_c']
        pack_max=packet['pack_temp_max_c']
        battery_current=packet['battery_current_amps']
        motor_current=packet['motor_current_amps']
        charge=packet['charge_pct']
f.close()
